name: CreateUser build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.LDAP.CreateUser/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.LDAP.CreateUser
      env_var_name_1: HiQ_AzureADTest_Address
      env_var_name_2: HiQ_AzureADTest_User
      env_var_name_3: HiQ_AzureADTest_Password
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.HIQ_AZUREADTEST_ADDRESS }}
      env_var_value_2: ${{ secrets.HIQ_AZUREADTEST_USER }}
      env_var_value_3: ${{ secrets.HIQ_AZUREADTEST_PASSWORD }}